name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'cinchdb/docs/**'
      - 'cinchdb/mkdocs.yml'
      - 'cinchdb/requirements-docs.txt'
      - 'cinchdb/.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cinchdb/docs/**'
      - 'cinchdb/mkdocs.yml'
      - 'cinchdb/requirements-docs.txt'
      - 'cinchdb/.github/workflows/docs.yml'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('cinchdb/requirements-docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cinchdb/requirements-docs.txt
          
      - name: Build documentation
        run: |
          cd cinchdb
          mkdocs build --strict --verbose
          
      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cinchdb/site

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4